name: setup xmake
description: Set up a xmake environment and add it to the PATH
author: OpportunityLiu
branding:
  icon: play
  color: green

inputs:
  token:
    required: false
    default: ""
    description: GITHUB_TOKEN
  xmake-version:
    required: true
    default: latest
    description: The version to use. Should be a semver range or 'latest'

runs:
  using: 'node12'
  main: 'dist/index.js'
  